jobs:
  orbs:
    python: circleci/python@2.1.1
  build:
    docker:
      - image: cimg/python:3.9-node
#    executor: python/default
    steps:
      - checkout
      - run: poetry install
      - run: pytest --snapshot-test

