jobs:
  build:
    docker:
      - image: cimg/python:3.9-node
    steps:
      - checkout
      - run:
          name: Poetry Install
          command: |
            LC_ALL=C.UTF-8
            LANG=C.UTF-8
            LANGUAGE=C.UTF-8
            poetry install --with=dev -vv
            echo $?
      - run: pytest

