jobs:
  build:
    docker:
      - image: cimg/python:3.9-node
    steps:
      - checkout
      - run: echo $LANG $LANGUAGE $LC_ALL
      - python/install-packages:
          pkg-manager: poetry
      - run: pytest --snapshot-test

